version: '3'

services:
  db:
    image: postgres:17
    restart: always
    ports:
      - 5433:5433
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: Administracion_Cliente
    volumes:
      - ./postgres:/var/lib/postgresql/data